--- #YAML:1.0
name:               Mojolicious-Plugin-Proxy
version:            0.2
abstract:           Proxy requests
author:
    - Marcus Ramberg<mramberg@cpan.org>
license:            artistic_2
distribution_type:  module
configure_requires:  {}
build_requires:  {}
requires:
    Mojolicious:  0
    perl:         5.008007
resources:
    bugtracker:   http://github.com/kraih/mojo/issues
    homepage:     http://mojolicious.org
    license:      http://dev.perl.org/licenses/
    MailingList:  http://groups.google.com/group/mojolicious
    repository:   http://github.com/kraih/mojo
no_index:
    directory:
        - t
        - inc
        - t
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
